# -*- coding: utf-8 -*-
"""Week4App.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umnr-Oz2i9Ff_v5MAwebfQuw6uv3Ifmn
"""

import numpy as np
from flask import Flask, request,render_template
import pickle

app = Flask(__name__,template_folder='template')
week4model = pickle.load(open('week4model.pkl', 'rb'))

@app.route('/')
def home():
    return render_template('indexW4.html')

@app.route('/predict',methods=['POST'])
def predict():
    '''
    For rendering results on HTML GUI
    '''
    int_features = [int(x) for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction = week4model.predict(final_features)

    output = prediction[0]

    return render_template('indexw4.html', prediction_text='The flower is {}'.format(output))

if __name__ == "__main__":
    app.run(debug=True)
