# -*- coding: utf-8 -*-
"""week4model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12c7H1ATmu3XjwwS9w5ppA6qYH3gwMUH4
"""

# Importing the libraries
import numpy as np
import pandas as pd
import pickle

from sklearn.datasets import load_iris
from sklearn import tree

iris= pd.read_csv("Iris.csv")
iris=iris.drop(columns="Id")

X = iris.loc[:,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y = iris.iloc[:, -1]

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)

# Saving model to disk
pickle.dump(clf, open('week4model.pkl','wb'))
# Loading model to compare the results
week4model = pickle.load(open('week4model.pkl','rb'))

print(week4model.predict([[2, 3, 5, 1]]))